apiVersion: v1
kind: Service
metadata:
  name: private-registry
  labels:
    name: private-registry
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30002
  selector:
    app: private-registry